dist: trusty
sudo: false

language: node_js

addons:
  chrome: stable

cache: npm

jobs:
  include:
    - stage: lint
      script: ng lint web-admin
      name: 'Lint web-admin project'
    - script: ng lint web-client
      name: 'Lint web-client project'
    - stage: unit tests
      script: ng test web-admin -c=ci
      name: 'Unit test web-admin project'
    - script: ng test web-client -c=ci
      name: 'Unit test web-client project'
    - stage: e2e tests
      script: ng e2e web-admin-e2e -c=ci
      name: 'E2E web-admin project'
    - script: ng e2e web-client-e2e -c=ci
      name: 'E2E web-client project'

deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
    branch: master
