sudo: false

language: node_js

addons:
  chrome: stable

cache: npm

install: npm ci

jobs:
  include:
    - stage: unit tests
      script: npm run postinstall.web && ng test web-client:ci
    - stage: e2e tests
      script: npm run postinstall.web && ng e2e web-client-e2e:ci
