dist: trusty
sudo: false

env:
  - APP_ID=web-admin
  - APP_ID=web-client

language: node_js

addons:
  chrome: stable

cache: npm

script:
  - ng test ${APP_ID} -c=ci
  - ng e2e ${APP_ID}-e2e -c=ci

jobs:
  include:
    - stage: deploy
      env: APP_ID=none
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run release
        on:
          branch: master
